### ISSUE TITLE
[文章][2022-03-26] 使用pyo3，从python调用rust代码

### ISSUE THREAD

**Issue by minikiller** [rustlang-cn/Rustt#10]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

```
---
> 原文链接: http://saidvandeklundert.net/learn/2021-11-18-calling-rust-from-python-using-pyo3/
> 
> 翻译：[minikiller](https://github.com/minikiller)
>
> 选题：[minikiller](https://github.com/minikiller)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by minikiller** [comment]
**预期完成时间** : 2周

**Comment by minikiller** [comment]
申请翻译，预期完成时间 2022-03-31

**Comment by sunface** [comment]
Approved, 选题 + 5 分

**Comment by sunface** [comment]
`@rubot`

翻译 + 27
