### ISSUE TITLE
[文章][2017-03-07] Rust类型系统图灵完备的证明

### ISSUE THREAD

**Issue by aresbit** [rustlang-cn/Rustt#105]
原文标题: Rust's Type System is Turing-Complete

原文链接: https://sdleffler.github.io/RustTypeSystemTuringComplete/

译文链接: 

---
**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
>  *[Rustt](https://rustt.org) 翻译计划，由 [RustCn](https://hirust.cn) 社区荣誉推出*
> 
> **翻译：[ChenYe](https://github.com/Ch3nYe)**
> 选题：[aresbit](GIthub个人链接)
>
> 原文链接: https://www.rust-lang.org
```

**Comment by Ch3nYe** [comment]
申请翻译 预计完成时间 2022-05-05

**Comment by sunface** [comment]
`@rubot`

选题 + 6

**Comment by sunface** [comment]
approved，选题由非组织成员提交，不加分

**Comment by sunface** [comment]
`@rubot`

翻译 + 35
