### ISSUE TITLE
[文章][2022-03-26] 从python调用rust-使用rust加速你的python代码

### ISSUE THREAD

**Issue by minikiller** [rustlang-cn/Rustt#12]
原文标题: Calling Rust from Python - speed up your Python using Rust

原文链接: http://saidvandeklundert.net/learn/2021-11-06-calling-rust-from-python/

译文链接:  https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-13%5D%20从python调用rust-使用rust加速你的python代码.md

---
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

---
**声明模版**

```
---
> 原文链接: http://saidvandeklundert.net/learn/2021-11-06-calling-rust-from-python/
> 
> **翻译：[ChenYe](https://github.com/Ch3nYe)**
> 选题：[minikiller](https://github.com/minikiller)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by Ch3nYe** [comment]
申请翻译，预期完成时间 2022-04-15

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by sunface** [comment]
`@rubot`

翻译 + 33
