### ISSUE TITLE
Rust萌新申请加入

### ISSUE THREAD

**Issue by qxzhou1010** [rustlang-cn/Rustt#121]
### 英文水平和写作能力

1. 多年前顺利通过了CET-6。
2. 研究生期间阅读了大量的英文论文，阅读能力还可以。
3. 研究生期间有撰写并成功发表多篇SCI英文论文经历。

### 预期多久翻译一篇文章?

半个月

### QQ 号

693662421

### 如果可以，请附上你之前比较得意的翻译作品( optional )

- 暂时没有

### 你对我们有哪些预期?

- 让我通过吧

**Comment by sunface** [comment]
抱歉，这两天有些忙。。回复晚了，欢迎加入～～
