### ISSUE TITLE
申请加入Rustt翻译小组

### ISSUE THREAD

**Issue by DawnMagnet** [rustlang-cn/Rustt#124]
### 英文水平和写作能力

大学英语六级水平，对Rust较为了解，现在在字节跳动从事Rust开发相关的实习工作，进行过有关技术方面的写作
<https://dawnmagnet.github.io/algorithm-station/>

### 预期多久翻译一篇文章?

一周

### QQ 号

2720579206

### 如果可以，请附上你之前比较得意的翻译作品( optional )

暂无

**Comment by sunface** [comment]
欢迎加入～～
