### ISSUE TITLE
[文章][2022-05-02] Rust 与 OpenCV

### ISSUE THREAD

**Issue by lxbwolf** [rustlang-cn/Rustt#127]
原文标题: Rust and OpenCV

原文链接: https://blog.devgenius.io/rust-and-opencv-bb0467bf35ff

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-05-08%5D%20Rust%20与%20OpenCV.md

---
**选题者须知**

1. 修改 issue 标题：将 `类型` 修改为为 *文章*、*系列*、*书籍* 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文标题、原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> *本文选自 [Rust 翻译计划](https://rustt.org)，由 [RustCn](https://hirust.cn) 荣誉推出*
> 
> **翻译：[Xiaobin.Liu](https://github.com/lxbwolf)**
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 原文链接: https://blog.devgenius.io/rust-and-opencv-bb0467bf35ff
```

**Comment by lxbwolf** [comment]
申请翻译
预计完成时间 2022-05-09

**Comment by sunface** [comment]
`@rubot` 

选题 + 7

**Comment by sunface** [comment]
`@rubot`

翻译 + 28
