### ISSUE TITLE
[视频][2022-05-04] 可视化 Rust 各数据类型的内存布局

### ISSUE THREAD

**Issue by trdthg** [rustlang-cn/Rustt#129]
原文标题: Visualizing memory layout of Rust's data types

原文链接: https://www.youtube.com/watch?v=rDoqT-a6UFg

译文链接:  https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-05-04%5D%20可视化%20Rust%20各数据类型的内存布局.md

---
**选题者须知**

1. 修改 issue 标题：将 `类型` 修改为为 *文章*、*系列*、*书籍* 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文标题、原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> *本文选自 [Rust 翻译计划](https://rustt.org)，由 [RustCn](https://hirust.cn) 荣誉推出*
> 
> **翻译：[trdthg](https://github.com/trdthg)**
> 选题：[trdthg](https://github.com/trdthg)
>
> 原文链接: https://www.rust-lang.org
```

**Comment by trdthg** [comment]
@sunface 申请翻译 预计完成时间 2022-05-04

**Comment by sunface** [comment]
`@rubot`

翻译 +35

**Comment by zavakid** [comment]
是否可以为视频增加字幕？

**Comment by trdthg** [comment]
> 是否可以为视频增加字幕？

基本完成 :tada:  [B站视频链接](https://www.bilibili.com/video/BV1KT4y167f1/)

**Comment by pycj** [comment]
枚举中不是有一个tag来标识具体的枚举值么，感觉文章中是不是没说出来

**Comment by trdthg** [comment]
> 枚举中不是有一个tag来标识具体的枚举值么

你指的应该是整数标记吧, 文章是跟着视频以及字幕走的, 没有突出重点(或者说没有明确指出), 算是一个不足. 
现在你应该比我熟悉, 要不提个 PR 改进下 🤗
