### ISSUE TITLE
申请加入 Rustt 翻译小组

### ISSUE THREAD

**Issue by Morgan279** [rustlang-cn/Rustt#141]
### 英文水平和写作能力

流利使用英文进行学术论文写作，硕士期间发表 CCF-A 类论文；目前在 PingCAP 参与 TiKV 侧云产品的相关研发工作，最近写的科普博文 “[用 Rust 从 0 到 1 实现一个最简化的 KV 存储引擎](https://blog.csdn.net/qq_36456827/article/details/125304612)”上了 Rust 语言周刊的精选文章。

### 预期多久翻译一篇文章?

半周

### QQ 号

377955050

**Comment by sunface** [comment]
最近翻译组先暂停了，社区即将上线，到时候统一整合在那里 :)

**Comment by Morgan279** [comment]
Get
