### ISSUE TITLE
我操你妈，你为什么盗我号点星星？

### ISSUE THREAD

**Issue by duanNT** [rustlang-cn/Rustt#146]
你们脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你们脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你们脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你们脑子有病吧？什么傻逼项目，写的什么玩意，你也配？
你们脑子有病吧？什么傻逼项目，写的什么玩意，你也配？

**Comment by abliger** [comment]
这也行

**Comment by sunface** [comment]
。。。这个项目涨星这么慢，我得多蠢才这么做？ 你可以找个网站查看下历史涨星记录。淡定吧！

**Comment by sunface** [comment]
再补充一下，也许你曾经点过，也许你的号被盗了，但是没有人会专门盗你的号来刷这个项目，总之，很莫名其妙，好歹你先调查清楚。

**Comment by sunface** [comment]
我仔细观察了下，每一个说刷星的，都隐藏了自己的资料。。。666
