### ISSUE TITLE
作者专门盗我号给他自己刷星星！

### ISSUE THREAD

**Issue by NicoleSherwood** [rustlang-cn/Rustt#150]
作者道德败坏，专门盗我号给他自己刷星星！！！！

**Comment by mrxiaozhuox** [comment]
搞 bot 有意思？私密账号别在这瞎 BB 求求了，关 ISSUE + 举报慢走不送。

**Comment by sunface** [comment]
> 搞 bot 有意思？私密账号别在这瞎 BB 求求了，关 ISSUE + 举报慢走不送。

才发现这个 issue :( ，黑子无处不在 = , =
