### ISSUE TITLE
[文章][2022-03-26] 半小时快速了解Rust

### ISSUE THREAD

**Issue by asur4s** [rustlang-cn/Rustt#16]
原文标题： A half-hour to learn Rust

原文链接： https://fasterthanli.me/articles/a-half-hour-to-learn-rust

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-28%5D%20半小时快速了解%20Rust.md

---
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

---
```
> 原文链接: https://fasterthanli.me/articles/a-half-hour-to-learn-rust
> 
> 翻译：[Asura](https://github.com/asur4s)
>
> 选题：[Asura](https://github.com/asur4s)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by asur4s** [comment]
@sunface 申请翻译，预期完成时间 2022-04-10

**Comment by sunface** [comment]
Approved, 选题 + 6

**Comment by sunface** [comment]
`@rubot`

翻译 + 30
