### ISSUE TITLE
[文章][2022-03-29] 架构实验 - 将一个前端项目使用 Rust 和 WASM 实现

### ISSUE THREAD

**Issue by allenli178** [rustlang-cn/Rustt#47]
原文标题: Architecture Experiment: Moving a front-end to Rust and WASM - Part 1

原文链接: https://nutsys.com/blog/architecture-experiment-rust-wasm-1/

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-21%5D%20架构实验：将前端迁移到%20Rust%20和%20WASM/%5B2022-04-21%5D%20架构实验：将前端迁移到%20Rust%20和%20WASM%20-%20第%201%20部分.md

---
**翻译者须知**

1. 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

---
**声明模版**

```
> 原文链接: https://nutsys.com/blog/architecture-experiment-rust-wasm-1/
> 
> 翻译：[子殊](https://github.com/allenli178)
> 选题：[子殊](https://github.com/allenli178)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by allenli178** [comment]
@sunface 申请翻译，预期完成时间 2022-04-08

**Comment by sunface** [comment]
`@rubot`

选题 + 7

**Comment by allenli178** [comment]
@sunface  我这篇博客还有两个部分 要不然我一起翻译了吧  翻译完成时间再推几天，我这周六有个比赛。

**Comment by sunface** [comment]
好～～没事

**Comment by sunface** [comment]
`@rubot`

翻译 + 80

**Comment by sunface** [comment]
`@rubot`

文章数 + 3

**Comment by sunface** [comment]
`@rubot`

翻译 + 0
文章数 + 3
