### ISSUE TITLE
[文章][2022-04-02] Rust中常见的错误处理范式

### ISSUE THREAD

**Issue by lxbwolf** [rustlang-cn/Rustt#57]
原文标题: Beginner's guide to Error Handling in Rust

原文链接: https://www.sheshbabu.com/posts/rust-error-handling/

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-17%5D%20Rust%20错误处理新手教程.md

--- 

**翻译者须知**

1. 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的 **顶部**
3. 填写下面的推广渠道

---
**声明模版**

```
> 原文链接: https://www.sheshbabu.com/posts/rust-error-handling/
> 
> **翻译：[Xiaobin.Liu](https://github.com/lxbwolf)**
>
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by lxbwolf** [comment]
申请翻译，预计完成时间 2022-04-18

**Comment by sunface** [comment]
`@rubot`

选题 + 7

**Comment by sunface** [comment]
`@rubott`

翻译 + 25

**Comment by sunface** [comment]
`@rubot`

翻译 + 25
