### ISSUE TITLE
[文章][2022-04-02] Building Relational Database on top of RocksDB in Rust

### ISSUE THREAD

**Issue by Cerdore** [rustlang-cn/Rustt#65]
原文标题: Building Relational Database on top of RocksDB in Rust

原文链接: https://blog.petitviolet.net/post/2021-05-25/building-database-on-top-of-rocksdb-in-rust

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-15%5D%20基于RocksDB使用Rust构建关系型数据库.md

---

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> 原文链接: https://blog.petitviolet.net/post/2021-05-25/building-database-on-top-of-rocksdb-in-rust
> 
> **翻译：[Cerdore](https://github.com/Cerdore/)**
>
> 选题：[Cerdore](https://github.com/Cerdore/)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by Cerdore** [comment]
申请翻译，预计完成时间：4.17日前。

**Comment by sunface** [comment]
`@rubot`

选题 + 7

**Comment by sunface** [comment]
`@rubot`

翻译 + 24
