### ISSUE TITLE
[文章][2022-04-02] Using Tokio Runtime for CPU-Bound Tasks

### ISSUE THREAD

**Issue by Akagi201** [rustlang-cn/Rustt#71]
原文标题：Using Rustlang’s Async Tokio Runtime for CPU-Bound Tasks

原文链接: https://thenewstack.io/using-rustlangs-async-tokio-runtime-for-cpu-bound-tasks/

译文链接：https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-20%5D%20使用%20Tokio%20处理%20CPU%20密集型任务.md

---

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

---
```
> 原文链接: https://thenewstack.io/using-rustlangs-async-tokio-runtime-for-cpu-bound-tasks/
> 
> **翻译：[trdthg](https://github.com/trdthg)**
>
> 选题：[Akagi201](https://github.com/Akagi201)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by trdthg** [comment]
@sunface 申请翻译，预计完成时间 2022-04-19

**Comment by sunface** [comment]
`@rubot`

选题 + 7
