### ISSUE TITLE
[文章][2022-04-04] 用 Rust 构建你自己的文本编辑器

### ISSUE THREAD

**Issue by trdthg** [rustlang-cn/Rustt#74]
原文链接: https://www.philippflenker.com/hecto/

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
---
> 原文链接: https://www.philippflenker.com/hecto/
> 
> **翻译：_该部分由 Approver 替换填写_**
>
> 选题：[trdthg](https://github.com/trdthg)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by trdthg** [comment]
@sunface 申请翻译，预期完成时间 2022-05-01

**Comment by chenfengyanyu** [comment]
上文链接打不开，楼主指的是这篇文章吗：[Build Your Text Editor With Rust!](https://medium.com/@otukof/build-your-text-editor-with-rust-678a463f968b)

**Comment by trdthg** [comment]
> 上文链接打不开，楼主指的是这篇文章吗：[Build Your Text Editor With Rust!](https://medium.com/@otukof/build-your-text-editor-with-rust-678a463f968b)

看了一下，应该是这篇 https://www.flenker.blog/hecto/
原作者好像把域名换了 philippflenker -> flenker
好像已经有人翻译了 https://paulden.site/posts/hecto/
