### ISSUE TITLE
[文章][2022-04-04] 使用 Rust 和 WebAssembly 在 48 小时内制作游戏

### ISSUE THREAD

**Issue by trdthg** [rustlang-cn/Rustt#75]
原文标题: Making a Game in 48 hours with Rust and WebAssembly

原文链接: https://ianjk.com/rust-gamejam/

译文链接: https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-27%5D%20使用%20Rust%20和%20WebAssembly%20在%2048%20小时内制作游戏.md

--- 

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
---
> 原文链接: https://ianjk.com/rust-gamejam/
> 
> **翻译：[子殊](https://github.com/allenli178)**
>
> 选题：[trdthg](https://github.com/trdthg)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by allenli178** [comment]
申请翻译，预期完成时间 2022-05-01

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by sunface** [comment]
`@rubot`

翻译 + 32
