### ISSUE TITLE
[文章][2022-04-04] 什么时候不应该使用 Rust ？

### ISSUE THREAD

**Issue by allenli178** [rustlang-cn/Rustt#80]
原文标题: When not to use Rust?

原文链接: https://kerkour.com/why-not-rust

译文链接：https://github.com/rustlang-cn/Rustt/blob/main/Articles/%5B2022-04-30%5D%20什么时候不应该使用%20Rust%20？.md

---

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> 原文链接: https://kerkour.com/why-not-rust
> 
> **翻译：[trdthg](https://github.com/trdthg)**
>
> 选题：[子殊](https://github.com/allenli178)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[RustCn](https://hirust.cn) 荣誉推出
```

**Comment by mrxiaozhuox** [comment]
这个标题有点机翻译那味儿了，改成 `什么时候不应该使用 Rust ？` 会不会更好？

**Comment by allenli178** [comment]
也可以吧 ，我改一下。

**Comment by FakeCore** [comment]
申请翻译,预计完成时间:2022-4-26

**Comment by FakeCore** [comment]
> 

抱歉,没注意看.我现在知道规则了:)

**Comment by trdthg** [comment]
@sunface 申请翻译，预期完成时间 2022-05-01

**Comment by sunface** [comment]
`@rubot`

翻译 +13
